spam-prevention:
  enabled: true
  warn-player: true
  cooldown-ms:
    s0: 1000
    s1: 2000
    s2: 3000
    s3: 4000
    s4: 5000
    s5: 6000

filter:
  enabled: true
  warn-player: true
  log:
    console: true
    local-file: true
    discord-webhook:
      enabled: false
      url: ""
  mute:
    enabled: true
    duration:
      s0: "30m"
      s1: "1h"
      s2: "2h"
      s3: "4h"
      s4: "8h"
      s5: "24h"
  rules:
    regex: []
    terms:
      whitelist: []
      blacklist: []