main: io.github.aleksandarharalanov.chatguard.ChatGuard
version: 2.0.0
name: ChatGuard
author: Beezle
website: github.com/AleksandarHaralanov/ChatGuard
description: Blocks blacklisted words, logs actions, prevents spam, mutes offenders, and enforces penalties.
softdepend: [Essentials]

commands:
  chatguard:
    description: All of ChatGuard's features in one command.
    usage: /chatguard
    aliases: [cg]

permissions:
  chatguard.*:
    children:
      chatguard.bypass: true
      chatguard.config: true
    description: All ChatGuard permissions.
    default: op
  chatguard.bypass:
    description: Allows player to bypass the ChatGuard protection.
    default: op
  chatguard.config:
    description: Allows player to reload the ChatGuard config.
    default: op