main: io.github.aleksandarharalanov.chatguard.ChatGuard
version: 2.3.0
name: ChatGuard
author: Beezle
website: github.com/AleksandarHaralanov/ChatGuard
description: Cancels messages containing blocked words, enforces Essentials temp. mutes, prevents chat spam, logs actions, implements escalating penalties.
softdepend: [Essentials]

commands:
  chatguard:
    description: All of ChatGuard's features in one command.
    usage: /chatguard
    aliases: [cg]

permissions:
  chatguard.*:
    children:
      chatguard.bypass: true
      chatguard.config: true
    description: All ChatGuard permissions.
    default: op
  chatguard.bypass:
    description: Allows player to bypass the ChatGuard protection.
    default: op
  chatguard.config:
    description: Allows player to reload and modify the ChatGuard configuration.
    default: op